# Generated by Django 2.1.2 on 2019-07-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20190705_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
