# Generated by Django 2.1.2 on 2019-07-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='id',
            field=models.CharField(default='line_2019750236e2e405ed', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.CharField(default='route_20197502360d101cb3', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
