# Generated by Django 2.1.2 on 2019-07-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0002_auto_20190705_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='id',
            field=models.CharField(default='line_2019710183353e29015a0', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.CharField(default='route_2019710183353e3cc8aee', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
