# Generated by Django 2.1.2 on 2019-07-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0002_auto_20190705_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='id',
            field=models.CharField(default='line_20197101628327ed85380', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.CharField(default='route_2019710162832089f34d2', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
