# Generated by Django 2.1.2 on 2019-07-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0003_auto_20190710_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='id',
            field=models.CharField(default='line_2019710163826fe067987', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.CharField(default='route_2019710163826e5da7342', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
