version: '2.4'
services:
  web:
    container_name: web
    build: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
    working_dir: /etc/nginx
    links:
      - python
  python:
    container_name: python
    build: ./docker/python
    ports:
      - 8000:8000
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html

volumes:
  data-volume:
