version: '2.4'
services:
  web:
    container_name: web
    build: ./docker/nginx
    ports:
      - 80:80
    networks:
      urbvan:
        ipv4_address: 10.10.0.2
    volumes:
      - ./app:/var/www/html
    working_dir: /etc/nginx
    links:
      - app
  app:
    container_name: python
    build: ./docker/python
    ports:
      - 8000:8000
    networks:
      urbvan:
        ipv4_address: 10.10.0.3
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html

volumes:
  data-volume:

networks:
  urbvan:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.10.0.0/24
