# Generated by Django 2.1.2 on 2019-07-03 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.CharField(default='line_2019731826247636ebc1', max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.CharField(default='route_201973182624d33d36e1', max_length=30, primary_key=True, serialize=False, unique=True)),
                ('direction', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lines.Line')),
                ('stations', models.ManyToManyField(to='stations.Station')),
            ],
        ),
    ]
